name: commercial_solvers
description: Set up commercial solvers in CI for testing purposes

runs:
  using: "composite"
  steps:
    # Download protected release asset
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: 'jgillis/restricted'
        version: 'perpetual'
        file: 'knitro-13.2.0-Linux-64.tar.gz'
        token: ${{ secrets.JGILLIS_RESTRICTED }}
      
