name: commercial_solvers
description: Set up commercial solvers in CI for testing purposes
inputs:
  token:
    description: GitHub token with access to the private repo
    required: true

runs:
  using: "composite"
  steps:
    - run: echo "$RUNNER_OS-$RUNNER_ARCH"
      shell: bash
    - uses: kanga333/variable-mapper@v0.3.0
      with:
        key: "${{runner.os}}-${{runner.arch}}"
        map: |
         {
            "Linux-X64": {"knitro": "knitro-13.2.0-Linux-64", "knitro_suffix": ".tar.gz"},
            "Windows-X64": {"knitro": "knitro-13.2.0-Win64", "knitro_suffix": ".zip"},
            "macOS-X64": {"knitro": "knitro-13.2.0-MacOS-64", "knitro_suffix": ".tar.gz"},
            "macOS-ARM64": {"knitro": "knitro-13.2.0-MacOS-ARM", "knitro_suffix": ".tar.gz"}
         }
        export_to: env
    # Download protected release asset
    - uses: dsaltares/fetch-gh-release-asset@1.1.0
      with:
        repo: 'jgillis/restricted'
        file: ${{env.knitro}}${{env.knitro_suffix}}
        token: ${{ inputs.token }}
    - uses: dsaltares/fetch-gh-release-asset@1.1.0
      with:
        repo: 'jgillis/restricted'
        file: 'artelys_lic_5007_casadi-dev_2022-08-24.txt'
        token: ${{ inputs.token }}
    - run: tar -xzf ${{env.knitro}}.tar.gz -C $RUNNER_TEMP
      shell: bash
      if: runner.os != 'Windows'
    - run: unzip ${{env.knitro}}.zip -d $RUNNER_TEMP
      shell: bash
      if: runner.os == 'Windows'
    - run: cp artelys_lic_5007_casadi-dev_2022-08-24.txt $RUNNER_TEMP
      shell: bash
      
    # Add to PATH
    - run: |
        echo "LD_LIBRARY_PATH=$RUNNER_TEMP/${{env.knitro}}/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "DYLD_LIBRARY_PATH=$RUNNER_TEMP/${{env.knitro}}/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
      if: runner.os != 'Windows'
      shell: bash
    - run: ls $RUNNER_TEMP/${{env.knitro}} && ls $RUNNER_TEMP/${{env.knitro}}/lib
      shell: bash
    - run: echo "$PATH"
      shell: bash
      
    - run: echo "PATH=$RUNNER_TEMP/${{env.knitro}}/lib;$PATH" >> $GITHUB_ENV
      if: runner.os == 'Windows'
      shell: bash
    - run: echo "LD_PRELOAD=$RUNNER_TEMP/${{env.knitro}}/lib/libiomp5.so"
      if: runner.os != 'Windows'
      shell: bash
    - run: echo "ARTELYS_LICENSE=$RUNNER_TEMP/artelys_lic_5007_casadi-dev_2022-08-24.txt" >> $GITHUB_ENV
      shell: bash
      
