name: test

on: push

jobs:
  main:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3.3.0
    - uses: ./
      with:
        token: ${{ secrets.JGILLIS_RESTRICTED }}
    - run: echo "$LD_LIBRARY_PATH"
    - run: pwd
    - run: ls
    - run: /home/runner/work/casadi/commercial_solvers/knitro-13.2.0-Linux-64/lib/libiomp5.so
