name: test

on: push

jobs:
  main:
    runs-on: [windows-latest,macos-11,self-hosted,ubuntu-20.04]

    steps:
    - uses: actions/checkout@v3.3.0
    - uses: ./
      with:
        token: ${{ secrets.JGILLIS_RESTRICTED }}
    - run: echo "$LD_LIBRARY_PATH"
    - run: echo "$PATH"